mt-sre/managed-tenants-cli

Makefile
docs/tenants/zz_schema_generated.md
managedtenants/core/addons_loader/sss.py
managedtenants/data/macros.j2
managedtenants/data/metadata.schema.yaml
managedtenants/data/selectorsyncset.yaml.j2
managedtenants/utils/ocm.py
setup.py
tests/README.md
tests/conftest.py
tests/data/test_paths.py
tests/sss/test_labels_and_annotations.py
tests/sss/test_manual_install_plan.py
tests/sss/test_sss_walker.py
tests/testdata/addons/test-operator/metadata/integration/addon.yaml
tests/testdata/addons/test-operator/metadata/production/addon.yaml
tests/testdata/addons/test-operator/metadata/stage/addon.yaml
tests/testutils/paths.py
tests/testutils/strategies.py
tests/utils/test_schema.py

`$ make lint` and `$ make test` work. :+1: 
Cherry-picked and adapted from  downstream `managed-tenants` repo.

Add tests/ directory, and cherry-pick latest changes from downstream

---

.pre-commit-config.yaml
managedtenants/cli/__init__.py

When running the CLI to perform bundles migration, the following Traceback was shown:
```bash
$managedtenants --environment production --addon-name rhods run tasks/utils/10_pkgman_to_bundle.py
Traceback (most recent call last):
File "/home/aasthana/go/src/github.com/managed-tenants/venv/bin/managedtenants", line 8, in <module>
sys.exit(main())
File "/home/aasthana/go/src/github.com/managed-tenants/venv/lib64/python3.9/site-packages/managedtenants/cli/__init__.py", line 188, in main
cli.run()
File "/home/aasthana/go/src/github.com/managed-tenants/venv/lib64/python3.9/site-packages/managedtenants/cli/__init__.py", line 128, in run
self._run()
File "/home/aasthana/go/src/github.com/managed-tenants/venv/lib64/python3.9/site-packages/managedtenants/cli/__init__.py", line 151, in _run …
```

Fix default value and provide better error message for --addons-dir flag.

---

.pre-commit-config.yaml
managedtenants/cli/__init__.py
managedtenants/core/addons_loader/__init__.py
managedtenants/utils/git.py
tests/utils/test_change_detector.py

In an effort to reduce our bundles-to-prod deployment time, adding this piece of code to modify the `addons_loader`.

[MTSRE-295] Add --only-changed flag to modify the addons_loader behavior and speedup pipeline.

---

.pre-commit-config.yaml
docs/tenants/zz_imageset_schema_generated.md
managedtenants/data/imageset.schema.yaml

The CPaaS team has agreed to provide the required fields for addon versioning as a part of imageset.
This PR adds addonRequirements, addonParameters and subOperators to imageset.
Addons such as RHOAMS currently cannot be migrated to mt-bundles and hence we're required to still keep these params in metadata as well.

[MTSRE-214]: Update imageset schema

---

docs/tenants/zz_schema_generated.md
managedtenants/core/addons_loader/addon.py
managedtenants/data/metadata.schema.yaml
managedtenants/data/selectorsyncset.yaml.j2
tests/addons/test_addon.py
tests/sss/test_subscription_config.py
tests/testdata/addons/test-operator/metadata/stage/addon.yaml

This PR allows tenants to create subscription configs for their addons by specifying them in the addon metadata file. (addon.yaml file) 
Todo after this is merged: 
- Update docs

[MTSRE-303] Allow subscription configs to be created

---

managedtenants/utils/ocm.py

This PR removed the `id` field from the payload while executing a PATCH operation against the OCM versions API. This would otherwise lead to the following error:
```
original error: {"kind":"Error","id":"400","href":"/api/clusters_mgmt/v1/errors/400","code":"CLUSTERS-MGMT-400","reason":"The following attributes are not allowed: 'id'","operation_id":"49b91421-924c-4cef-a2ed-020f3a34dfa1"}
```
This fix has been tested locally against the OCM API.

ocm: Fix addon version patch operation

---

.pre-commit-config.yaml
managedtenants/core/addons_loader/addon.py
managedtenants/utils/general_utils.py
managedtenants/utils/ocm.py

The current approach is to use `metadata.addonImageSetVersion`. However, the problem with this is that the said field could be set to `latest`, which causes issues when posting data to OCM, as `latest` is not recognized as a version. Instead, this PR parses the version directly from the imageset name instead of relying on what is set in the metadata

Parse imageset version from imageset name for OCM upsert

---

docs/tenants/zz_imageset_schema_generated.md
managedtenants/data/imageset.schema.yaml
managedtenants/utils/ocm.py

Removes the `items` field from `imageset.addOnParameters`, instead, array items can directly be appended to `imageset.addOnParameters`, similar to metadata.addOnParameters.
The OCM upsert function has been modified to append array items to the `items` field instead, to comply with the OCM API Spec.
Tested and verified locally against OCM stage:
```bash
❯ ./venv/bin/managedtenants --environment stage --addons-dir addons --addon-name reference-addon run --debug tasks/deploy/30_ocm_upsert.py
Loading stage...
Loading stage OK
== TASKS =======================================================================
tasks/deploy/30_ocm_upsert.py:OcmUpsert:reference-addon:stage...
OCM upsert for reference-addon
tasks/deploy/30_ocm_upsert.py:OcmUpsert:reference-addon:stage OK
```

Make imageset.addOnParameters consistent with metadata.addOnParameters

---

managedtenants/bundles/utils.py

- Explicitly convert path object to string before calling .split()
- Change yaml loader

Some misc changes:

---

Dockerfile.test
Makefile
pr_check.sh

Exposes the docker cmd and docker sock to the test container.
Fixes the failing tests in https://github.com/mt-sre/managed-tenants-cli/pull/72.

dind changes for dockerfile.test

---

managedtenants/bundles/bundle_builder.py
managedtenants/bundles/index_builder.py

This PR introduces a new argument to  `build_push_bundle_images_with_deps` and `build_push_index_image` which determines whether to ensure the passed quay repo's presence or not.

conditionally ensure quay repo's presence

---

managedtenants/schemas/shared/addon_parameters.json

When a user enters an invalid value for the add-on parameter, they are returned an error message with the regular expression that the parameter failed to match. This is not a good user experience, especially if the regex is long and complex. 
I've filed an MR ([uhc-clusters-service!3547](https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3547)) to clusters-service that adds a validation_error_message field that AddOn developers can use to return a custom error message should an invalid parameter value be provided.
This PR adds the new field to the metadata schema, so that the cli can pass this data to ocm.

adding validation_err_msg to addOnParameter schema

---

.pre-commit-config.yaml
managedtenants/bundles/ci.py
managedtenants/bundles/utils.py
managedtenants/cli/__init__.py

This is to allow a better testing story between `py-mtcli` and `managed-tenants-bundles`. Here is the new workflow for dev:
```bash
$ make develop
$ source .venv/bin/activate
(venv) $ managedtenants --addons-dir=../managed-tenants-bundles/addons --addon-name gpu-operator --dry-run bundles
(venv) $ managedtenants --addons-dir=../managed-tenants-bundles/addons --dry-run bundles
(venv) $ managedtenants --addons-dir=../managed-tenants-bundles/addons --only-changed --dry-run bundles
```

[MTSRE-427] Migrate ci.py script to py-mtcli.

---

.pre-commit-config.yaml
managedtenants/core/addons_loader/addon.py
managedtenants/data/selectorsyncset.yaml.j2
tests/addons/test_addon.py
tests/sss/test_federated_metrics.py
tests/sss/test_subscription_config.py
tests/testdata/addons/mock-operator-with-imagesets/addonimagesets/stage/mock-operator.v1.0.0.yml
tests/testdata/addons/test-operator/metadata/stage/addon.yaml
tests/testutils/addon_helpers.py

the YAMLloader renders values in the jinja template without quotes. Now that perfectly works for generic strings but messes up when the value is something which can be interpreted as a non-string type like, true/false, any int like 2, 42, etc. 
But we want to deterministically ensure that under subscriptionConfig, the value, even if provided with "true", "false", "1", "2", etc. ends up explicitly getting interpreted as a string and the block chomping indicator `|-` in this PR accomplishes that
Example:
**Before this PR**
**_Regular succeeding situations_**
_Input_
```json
{"env": {"name": "healthy", "value": "yes"}}
```
_Intermediate Representation_
```yaml
env:
name: healthy ### parsed by YAML as a string
value: yes ### parsed by YAML as a string
```
_Dumped YAML Output_
```yaml
env: …
```

MTSRE-419 | fix bool misinterpretation

---

Pipfile

CI pr_check runs have been failing since `pytest 7.0.0` was released. The `Pipfile` should pin the version, but is a patch version behind which could be preventing proper installation. This change will just enforce that `pytest` is at the latest `6.X.X` version.
See [here](https://github.com/pytest-dev/pytest/issues/9608) for background on why `pytest 7.0.0` is incompatible with `Python 3.9.6`.

Ensuring `pytest <7.0.0` when running tests in CI

---

managedtenants/schemas/imageset.schema.yaml

The pattern we follow should allow for:
```
<addon-id>.v<semantic-version>
```
Examples:
rhoams.v1.16.0
managed-odh.v2.0.1-pre1
This patch adds a regex to minimally validate the expected pattern.
Related to CPAAS-3281

Adding pattern to ImageSet name

---

managedtenants/core/addons_loader/__init__.py
managedtenants/core/addons_loader/addon.py

Modifed Addon loader to error out when `addonImageSetVersion` is set to anything apart from `"latest"`. See https://issues.redhat.com/browse/MTSRE-453

[MTSRE-453] Allow only `latest` for addonImageSetVersion

---

docs/tenants/zz_metadata_schema_generated.md
managedtenants/schemas/metadata.schema.yaml
managedtenants/utils/ocm.py

When installing an addon that needs access to AWS resources on an STS
cluster, the addon needs to announce which service account to use for
generating the token and the list of policy permissions required.
This will allow ROSA to guide the user through the role/policy creation
process, and allow OCM to validate that the authentication works when
the user supplies the resulting IAM role ARN.
* https://issues.redhat.com/browse/SDA-5367
* https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3783
* https://github.com/openshift-online/ocm-api-model/pull/484

OCM: Add attributes necessary for STS addons

---

managedtenants/schemas/metadata.schema.yaml

- Updated metadata schema to permit `operatorname` longer than 32 characters.

[MTSRE-472] Extending `operatorName` valid length

---

managedtenants/data/selectorsyncset.yaml.j2

The Secret needs a deterministic name, but not need to make it related to the addon itself, as we creat it in the namespace of the addon anyway.
This will make it easier to find the secret, regardless the operator looking for it.

Changing the pullSecret Secret name

---

managedtenants/schemas/shared/addon_parameters.json
tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml

Fixes: JIRA - [SDA-5638](https://issues.redhat.com/browse/SDA-5638)
The keyword used in the "Model" for specifying requirements inside `resource_requirement` parameters is `requirements` not `addOnRequirements`
Signed-off-by: Juan Miguel Olmo Martínez jolmomar@redhat.com

Fix keyword in parameter type <resource_requirement>

---

docs/tenants/zz_metadata_schema_generated.md
managedtenants/core/addons_loader/addon.py
managedtenants/data/selectorsyncset.yaml.j2
managedtenants/schemas/metadata.schema.yaml
tests/addons/test_addon.py
tests/sss/test_catalogue_source.py
tests/testdata/addons/test-operator/metadata/integration/addon.yaml

This PR adds a new attribute (`additionalCatalogSources`) in the addon metadata file.
Jira: https://issues.redhat.com/browse/MTSRE-485

[MTSRE-485] Add a new `additionalCatalogSources` attribute in the addon metadata file

---

docs/tenants/zz_metadata_schema_generated.md
managedtenants/schemas/metadata.schema.yaml
managedtenants/utils/ocm.py

https://issues.redhat.com/browse/SDA-5359
- A managedService field was added to the addons schema, which will be used to determine if the add-on is a managed service. 

adding managedService flag to indicate if an addon is a managed service

---

managedtenants/core/addons_loader/addon.py

We implemented this functionality for test only, now we need the
SelectorSyncSet to be the regular one and do the proper migration.

Stop creating Addon CR in the SelectorSyncSet

---

managedtenants/core/addons_loader/addon.py
tests/addons/test_addon.py

Added the following validation checks:
- `secret` names should be unique
- `pullSecretName` should be one of `secrets`'s names

[MTSRE-481] Added `secrets` and `pullSecretName` validation

---

managedtenants/bundles/addon_bundles.py
managedtenants/data/selectorsyncset.yaml.j2
tests/sss/test_catalogue_source.py
tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml

Fixes: [MTSRE-497](https://issues.redhat.com/browse/MTSRE-497)
This PR modifies the SSS jinja template to use the `pullSecretName` attribute as a `secret` parameter in the created catalog source objects.

conditionally inject secrets to the created catalog src objects

---

managedtenants/schemas/shared/subscription_config.json

Adds regex validation for addon environment variable name attribute. We need this validation since environment variable names should consist solely of uppercase letters, digits, and ‘_’ and do not begin with a digit.

add regex validation for addon environment variable name attribute

---

managedtenants/bundles/binary_deps.py
managedtenants/bundles/bundle.py
managedtenants/bundles/index_builder.py
managedtenants/cli/__init__.py

Delay pulling sretoolbox binaries to the moment when they are needed.

LazyBin fix, pull binaries only when they are ran.

---

.pre-commit-config.yaml
managedtenants/schemas/shared/addon_requirements.json

- Made `aws.security_group_filters` available as a data key for addon requirements.

feat: adding aws.security_group_filters to requirements

---

managedtenants/schemas/shared/addon_requirements.json

Signed-off-by: Nico Schieder <nschieder@redhat.com>
Renames `aws.security_group_filters` to `compute.security_group_filters` introduced in https://github.com/mt-sre/managed-tenants-cli/pull/143

Rename aws.security_group_filters to compute.security_group_filters

---

managedtenants/bundles/docker_api.py
managedtenants/bundles/index_builder.py
tests/bundles/test_index_builder.py

The codebase contained a bug where validating that a bundle image has Size > 0 is sufficient to ensure a bundle is properly built, but this is not sufficient for an index image.
This is because the index image will always have Size > 0 as it contains a whole alpine or busybox container depending on OPM's version used.
This fix proposes a deeper inspection by extracting the `/database/index.db` sqlite3 file from a container and ensuring the `properties` table contains bundles metadata.

Fix: Ensure SQL catalog contains bundles.

---

docs/tenants/zz_metadata_schema_generated.md
managedtenants/data/selectorsyncset.yaml.j2
managedtenants/schemas/metadata.schema.yaml
tests/sss/test_federated_metrics.py

The ServiceMonitor generated by py-mtcli has some flaws:
- `portName` is not configurable
- Not using the `caFile` present in the "master" prometheus server (the one living in `openshift-monitoring`)
- Was not using a `bearerTokenFile`
All ServiceMonitor in managed openshift follow the same structure as the `openshift-apiserver` one, which is how we should model our configurations as well:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
annotations:
include.release.openshift.io/ibm-cloud-managed: "true"
include.release.openshift.io/self-managed-high-availability: "true"
include.release.openshift.io/single-node-developer: "true"
name: openshift-apiserver
namespace: openshift-apiserver
spec:
endpoints:
- bearerTokenFile: …
```

[MTSRE-528] Fix serviceMonitor CR in sss.

---

docs/tenants/zz_imageset_schema_generated.md
docs/tenants/zz_metadata_schema_generated.md
docs/tenants/zz_mtbundles_schema_generated.md
managedtenants/schemas/imageset.schema.yaml
managedtenants/schemas/metadata.schema.yaml
managedtenants/schemas/mtbundles.schema.yaml

Signed-off-by: Ankit kurmi <akurmi@redhat.com>
- Adding description to all the JSON schema fields in managed-tenants [MTSRE-290](https://issues.redhat.com/browse/MTSRE-290)

[MTSRE-290] Add description to all JSON schema fields in managed-tenants

---

managedtenants/bundles/index_builder.py

Changed the tag format used by bundles to digest format.

MTSRE-489 Bundles use digest format

---

managedtenants/core/addons_loader/sss.py
managedtenants/data/selectorsyncset.yaml.j2
tests/sss/test_catalogue_source.py
tests/sss/test_subscription_config.py
tests/testutils/addon_helpers.py

OCM is responsible to create the Addon CR in clusters. We can safely remove it from the generated SSS when the `ADDON.manager == AddonManager.ADDON_OPERATOR` to avoid confusion and unecessary feature parity PRs.
ref: https://github.com/mt-sre/managed-tenants-cli/pull/158
cc @apahim

Remove Addon CR from the generated SSS as it is created by OCM.

---

managedtenants/data/selectorsyncset.yaml.j2

- Currently the SSS creates the CatalogSource in the openshift-marketplace namespace. We should use the targetNamespace instead:
https://github.com/mt-sre/managed-tenants-cli/blob/main/managedtenants/data/selectorsyncset.yaml.j2#L117
- addon-operator already does the right thing:
https://github.com/openshift/addon-operator/blob/main/internal/controllers/addon/phase_ensure_catalogsource.go#L33-L49
Added fix for the jinja template.

[MTSRE-534] Create CatlogSource in the targetNamespace

---

managedtenants/utils/ocm.py

Dont send rollback_migration attr as part of the json payload as part of enabling addon migration

Modify ocm client

---

managedtenants/bundles/index_builder.py

Building index images with UBI base image for compliance.
Please view ticket for more info: https://issues.redhat.com/browse/MTSRE-540

[MTSRE-540] Build index images with UBI base image.

---

managedtenants/data/selectorsyncset.yaml.j2

Signed-off-by: Nico Schieder <nschieder@redhat.com>
Adds a `NetworkPolicy` to every SyncSet to allow explicit access to the CatalogSource pods.
Without this policy in place, addon firewalling might prevent access, which in turn prevents the addon from being upgraded.

Create a NetworkPolicy to grant explicit access to addon CatalogSources

---

Dockerfile.test

Bumping base image in Dockerfile.test to ubi9 to avoid dependency issues.
eg. https://ci.ext.devshift.net/job/mt-sre-managed-tenants-cli-gh-pr-check/388/console

Bumping base image in Dockerfile.test to ubi9

---

Makefile
pr_check.sh

Moving named volume logic to Makefile's `test` target.

refactor: Moving named volume from pr_check.sh to `test` target

---

managedtenants/utils/ocm.py

This PR adds a new method to check if addon migration exists in ocm. The idea is to use this method in the mt gitlab repo instead of `get_addon_migration` which raises an exception on 404's.

new method to check if addon migration exists

---

managedtenants/bundles/cli.py
managedtenants/bundles/index_builder.py
managedtenants/cli/__init__.py

fix for https://issues.redhat.com/browse/MTSRE-586
Next step:
- Add `--build-with tag` in the `check` target here: https://gitlab.cee.redhat.com/service/managed-tenants-bundles/-/blob/main/Makefile#L29-35

[MTSRE-586] fix: use `--build-with tag` in dry-run mode

---

.pre-commit-config.yaml
managedtenants/schemas/metadata.schema.yaml

- Fixed 'link' validation regex to accept `#` anchor tags.

[MTSRE-592] fix: allowing anchor tags '#' in addon 'link' field

---

managedtenants/data/selectorsyncset.yaml.j2

added `upgradeStrategy` for additionalCatalogSources.
https://issues.redhat.com/browse/MTSRE-600

[MTSRE-600] added upgradeStrategy for additionalCatalogSources

---

managedtenants/schemas/shared/addon_parameters.json

- `managedtenants/schemas/shared/addon_parameters.json`
Added `editable_direction` to parameter and `rank` to parameter options

Adding fields to control add-on option's editable direction

---

.pre-commit-config.yaml
docs/tenants/zz_metadata_schema_generated.md
managedtenants/schemas/shared/addon_parameters.json
setup.py
tests/testdata/addons/mock-operator-with-imagesets/addonimagesets/stage/mock-operator.v1.0.1.yml

Adds the following validations for addon parameters:
- If `editable_direction` is defined, then `options` must be defined and non-empty
- For every `option` _o_, if _o.rank_ is defined, then _o.rank_ must be non-negative

fix: fail early when addon paramter has disallowed property combinations

---

.pre-commit-config.yaml
Makefile

A bunch of repetitive errors have been happening on the build_tag task on Jenkins.
And the logs suggest that it's happening during twine tries to upload the package to PyPI. The errors seems to originate from uploading the same distributions of py-mtcli again on PyPI.
```sh
14:26:05 WARNING  Error during upload. Retry with the --verbose option for more details. 
14:26:05 ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
14:26:05          File already exists. See https://pypi.org/help/#file-name-reuse for    
14:26:05          more information.                                                      
14:26:05 make: *** [Makefile:68: release] Error 1
14:26:05 Build step …
```

fix: skip existing files in dist/ while making a release to avoid PyPI distribution conflcts

---

managedtenants/bundles/cli.py
managedtenants/cli/__init__.py

Accept a new command line parameter which lists the addons for which imageset has to be created when building index images.

bundle builder: accept imageset enabled addons as a command line arg.

---

managedtenants/schemas/metadata.schema.yaml

Update the schema to use the regex from https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels 

Update metadata schema

---

managedtenants/schemas/shared/addon_requirements.json

Adding support for specifying taints and label requirements in accordance with [SDA-6531](https://issues.redhat.com/browse/SDA-6531)
Updated the schema for addon requirements

adding support for specifying taints and label requirements

---

managedtenants/schemas/metadata.schema.yaml
tests/testdata/addons/mock-operator-with-duplicate-keys/metadata/stage/addon.yaml
tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml
tests/testdata/addons/mock-operator-with-only-required-attrs/metadata/stage/addon.yaml
tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml

- deprecate channels parameter

remove channels parameter

---

managedtenants/utils/ocm.py
tests/utils/test_ocm.py

Changed `namespaces` to `namespace`.
API reference: https://api.openshift.com/#/default/post_api_clusters_mgmt_v1_addons
Ref:
1. 
```
"credentials_requests": [
{
"name": "string",
"namespace": "string",
"policy_permissions": [
"string"
],
"service_account": "string"
}
]
```
2. Console output: 
```
{"kind":"Error","id":"400","href":"/api/clusters_mgmt/v1/errors/400","code":"CLUSTERS-MGMT-400","reason":"Bad request body: json: cannot unmarshal object into Go struct field AddOnNamespace.namespaces.name of type string","operation_id":"9bda96d7-02d1-4657-b894-949a72450e9a"}
```

fix: ADDON_KEYS mapping to right ocm keys

---

.pre-commit-config.yaml
managedtenants/utils/ocm.py

Clusters-service ignores `order` updates to addon parameters with `order=0` since `0` is a useful default in go. This starts all parameter lists at index `1` so that updates by tenants are actually reflected in OCM.

[MTSRE-712] fix: index addon parameters starting from 1

---

managedtenants/utils/ocm.py

AS APIs expect the req. payload to contain `addOnParameters` as 
```json
{
"parameters": [<parameter_obj_1>, <parameter_obj_2>, ....]
}
```
(directly as a slice of parameter-objects), 
unlike the old CS-API which expected `addOnParameters` as: 
```json
{
"parameters": {
"items": [<parameter_obj_1>, <parameter_obj_2>, ....]
}
}
```
This PR adds the support for tweaking the addOnParameters with respect to the API being called (AS or CS)

fix: modify addon payload compliant with AS whenever talking to AS APIs

---

managedtenants/bundles/binary_deps.py

Bumping OPM version from `1.19.5` to `1.24.0`.

[MTSRE-796] Bump up OPM version to 1.24.0

---

managedtenants/schemas/shared/addon_requirements.json

Overall the validations on addon_requirements are not perfect, some keys
are not allowed when using machine_pool, or cluster type. This commit
addresses the values for data and adds some validations (numbers,
versions) and missing descriptions.
Version pattern: https://rubular.com/r/A2Ie7CE0VTmpIx
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

feat: custom validations for resource

---

managedtenants/utils/ocm.py
tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml
tests/utils/test_ocm.py

Include common_labels and common_annotations attribute in the json addon payload to OCM.
Signed-off-by: Ashish <asnaraya@redhat.com>

feat: update ocm-client

---

managedtenants/schemas/shared/addon_requirements.json

Signed-off-by: Yashvardhan Kukreja <yash.kukreja.98@gmail.com>
the 'id' field in under the machine pool config is meant to be used by OCM managed-service to take decisions around the scaling or creation of existent or non-existent machine pool respectively.

fix: allow machine pool resources to have 'id' field under them as a part of requirements config

---

managedtenants/core/addons_loader/package.py
managedtenants/data/selectorsyncset.yaml.j2
managedtenants/schemas/metadata.schema.yaml
managedtenants/utils/ocm.py
tests/sss/test_federated_metrics.py

introduces the support for the `monitoringStack` field in the metadata schema for specifying the config for the monitoring stack CR to be utilised by the addon-operator in runtime. 

[MTSRE-515] feat: introduce monitoringStack API to the metadata

---

managedtenants/core/addons_loader/package.py
managedtenants/utils/ocm.py

CS and AS are supposed to receive the `metricsFederation` config and `monitoring_stack` config respectively as well since SyncSets came into the picture. Due to the absence of this, no tenant in the fleet was able to provision resources oriented with metricsFederation since they were migrated to SyncSets.
This PR achieves that.
Note: this PR takes care of the fact that the addons-service and cluster-service aren't deployed to support for the `metrics_federation` and `monitoring_stack` fields. 
Hence, the `UNSUPPORTED_FIELDS_AS` and `UNSUPPORTED_FIELDS_CS` are involved in the PR.
In the future, once things are well-deployed and updated on CS's and AS's sides, all we need to do is to just update the values of `UNSUPPORTED_FIELDS_AS` and `UNSUPPORTED_FIELDS_CS` variables.

feat: feed metrics_federation / monitoring_stack config to OCM API calls of CS and AS accordingly

---

managedtenants/schemas/shared/addon_parameters.json

- modified managedtenants/schemas/shared/addon_parameters.json, added order to parameter schema

chore: add order to addon parameters schemas

---

managedtenants/utils/ocm.py

In ocm client's sanitize method only delete key if its present in the object.

fix: ocm client sanitize method

---

managedtenants/bundles/package_builder.py

Updated kubectl package to latest Package Operator v1.6.3

Update kubectl-package to v1.6.4

---

managedtenants/bundles/package_builder.py

- modified X
- modified Y
- modified Z

Fix package validation

---

managedtenants/utils/ocm.py

Wrapping `AddOnParameters` payload under "items" key for addons service.

Wrap addon parameters payload in "items" for AS

---

managedtenants/bundles/index_builder.py

- modified X
- modified Y
- modified Z

[MTSRE-1734] fix: bump index image base

---

managedtenants/data/selectorsyncset.yaml.j2

[MTSRE-1698](https://issues.redhat.com/browse/MTSRE-1698)
- modified X
- modified Y
- modified Z

feat: PDI template changes for PDO service orchestration

---

managedtenants/bundles/binary_deps.py

Jira: [MTSRE-1846](https://issues.redhat.com/browse/MTSRE-1846)
- bumping `operator-sdk` version to `1.21.0`

[MTSRE-1846] Upgrading operator-sdk version to 1.21.0
