- Pipfile
- managedtenants/__init__.py
- managedtenants/core/addons_loader/addon.py
- managedtenants/core/addons_loader/bundle.py
- managedtenants/core/addons_loader/sss.py
- managedtenants/core/runner.py
- managedtenants/core/tasks_loader/post_task.py
- managedtenants/core/tasks_loader/pre_task.py
- managedtenants/core/tasks_loader/task.py
- managedtenants/core/version.py
- managedtenants/data/macros.j2
- managedtenants/data/metadata.schema.yaml
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/utils/ocm.py
- managedtenants/utils/schema.py
- setup.py
> Cherry pick latest changes from downstream

- README.md
> [MTSRE-184] Update docs

- setup.py
> Add entry_points in setup.py

- MANIFEST.in
- setup.py
> Add MANIFEST.in to include package data

- docs/tenants/zz_schema_generated.md
- managedtenants/data/metadata.schema.yaml
- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_federated_metrics.py
- tests/sss/test_labels_and_annotations.py
- tests/sss/test_sss_walker.py
> Cherry pick from GitLab mr #1212

- Pipfile
- setup.py
> Make package work with python 3.6

- README.md
> Fix: typos associated with README

- managedtenants/data/imageset.schema.yaml
> update imageset schema with subscription config object

- .pre-commit-config.yaml
- docs/tenants/zz_imageset_schema_generated.md
- docs/tenants/zz_schema_generated.md
- managedtenants/core/addons_loader/addon.py
- managedtenants/data/metadata.schema.yaml
- managedtenants/data/selectorsyncset.yaml.j2
- tests/addons/test_addon.py
- tests/sss/test_subscription_config.py
- tests/testdata/addons/mock-operator-with-imagesets/addonimagesets/stage/mock-operator.v1.0.0.yml
- tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml
- tests/testdata/addons/test-operator/metadata/stage/addon.yaml
- tests/testutils/addon_helpers.py
Allow addon imageset's to define subscription configs
> Imageset subscription config support

- docs/tenants/zz_imageset_schema_generated.md
- managedtenants/data/imageset.schema.yaml
> Update ImageSet schema to fix Addon parameters

- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_subscription_config.py
> Update SSS jinja template to add subscription config info for the addon CR

- .pre-commit-config.yaml
- docs/tenants/zz_schema_generated.md
- managedtenants/data/metadata.schema.yaml
- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_catalogue_source.py
- tests/sss/test_deadmanssnitch.py
- tests/sss/test_pagerduty.py
- tests/testdata/addons/test-operator/metadata/stage/addon.yaml
- tests/testutils/addon_helpers.py
> MTSRE-279 | Move deadmanssnitch configuration under the metadata schema

- Dockerfile.test
- Makefile
- hack/yamlschema2md.py
- managedtenants/cli/__init__.py
- managedtenants/core/addons_loader/addon.py
- managedtenants/utils/schema.py
- setup.py
- tests/sss/test_catalogue_source.py
- tests/sss/test_deadmanssnitch.py
- tests/sss/test_pagerduty.py
- tests/testutils/addon_helpers.py
Still gotta figure out why `pipenv lock --pre --clear` is breaking things
> add: pipenv fix (temporary)

- .gitignore
- Dockerfile.test
- Makefile
- pr_check.sh
Required to exit early on CI errors.
> Fix make early exit.

- docs/tenants/zz_imageset_schema_generated.md
- docs/tenants/zz_schema_generated.md
- managedtenants/data/imageset.schema.yaml
- managedtenants/data/metadata.schema.yaml
Migrating from downstream (MR #1208).
To sync with `api.openshift.com`
> Fix addon suboperators required property names.

- managedtenants/bundles/binary_deps.py
- managedtenants/bundles/bundle_utils.py
- managedtenants/bundles/index_image_utils.py
- managedtenants/bundles/utils.py
- managedtenants/utils/gitlab_client.py
Adds some misc methods and functions which are required for migrating the code in mt-bundles repo
> More bundles changes

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/schemas/metadata.schema.yaml
- tests/testdata/addons/mock-operator-with-bundles/bundles/1.0.0/mock-operator.v1.0.0.clusterserviceversion.yaml
- tests/testdata/addons/mock-operator-with-bundles/metadata/stage/addon.yaml
- tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml
> drop support for SingleNamespace

- managedtenants/schemas/metadata.schema.yaml
Reference: https://olm.operatorframework.io/docs/best-practices/channel-naming/#recommended-channel-naming
> Adding OLM reccomended channel names

- managedtenants/bundles/bundle_builder.py
> MTSRE-433 | fix: versions to be sorted by Version Parser instead of them being lexicographically sorted

- managedtenants/schemas/mtbundles.schema.yaml
Proposal to add optional `addons` property to mtbundles schema
> [MTSRE-415] Add optional `addons` property to mtbundles schema

- Makefile
- Pipfile
- setup.py
> Fix docker dependency was dev-only.

- managedtenants/utils/ocm.py
Fixes: https://issues.redhat.com/browse/MTSRE-436.
Check and create an addon if not already present  before creating a new addon version.
> Ocm api: check and create an addon before posting a new addon version

- managedtenants/schemas/shared/addon_parameters.json
- tests/testdata/addons/mock-operator-with-imagesets/metadata/stage/addon.yaml
New parameter type <resource_requirement>
JIRA - SDA-5400
Introduced AddOnRequirements inside addon parameter options
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>
> New parameter type <resource_requirement>

- managedtenants/utils/ocm.py
- make `_api` method return raw response object on http requests
- refactor `_addon_exists` method to return boolean values based on
exception raised.
> ocmCli changes

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/schemas/metadata.schema.yaml
- managedtenants/utils/ocm.py
- tests/addons/test_addon.py
- tests/testdata/addons/mock-operator-with-secrets/bundles/1.0.0/mock-operator-secrets.v1.0.0.clusterserviceversion.yaml
- tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml
- tests/testutils/addon_helpers.py
This PR adds two new attributes (`secrets` and `pullSecretName`) in the addon metadata file.
Jira: https://issues.redhat.com/browse/MTSRE-481
> [MTSRE-481] Added new `secrets` and `pullSecretName` attributes in addon metadata file

- managedtenants/core/addons_loader/addon.py
- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_catalogue_source.py
- tests/testdata/addons/test-operator/metadata/integration/addon.yaml
Make pullsecret reference in catalog src work with legacy "pullSecret" attribute
> Conditionally select secret name in the catalog src 

- managedtenants/core/addons_loader/sss.py
- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_secrets.py
Updated jinja template to create `kind: Template` and added tests for same.
> [MTSRE-481] Updated jinja template

- managedtenants/data/selectorsyncset.yaml.j2
- tests/sss/test_secrets.py
Fixed indentation in the jinja template.
> [MTSRE-481] Fixed Indentation in the jinja template

- managedtenants/bundles/index_builder.py
Guilty of not testing my last PR enough. When in `--dry-run` the index image is always broken locally and `/database/index.db` is empty.
Disabling sql catalog validation.
> Disable sql catalog check.

- managedtenants/schemas/metadata.schema.yaml
> remove regex validation for the additional catalog source image

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/core/addons_loader/addon.py
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/schemas/metadata.schema.yaml
- tests/addons/test_addon.py
- tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml
- Added an optional `destinationSecretName` field to `addon.yaml` schema.
- Removed `vaultPath` regex.
> [MTSRE-481] Added `destinationSecretName` field

- .linters/pylint
- .pre-commit-config.yaml
- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/schemas/metadata.schema.yaml
- managedtenants/utils/ocm.py
- tests/sss/test_sss_syncset_migration.py
- tests/testutils/addon_helpers.py
> MTSRE-499 | add support for syncsetMigration field in addon metadata

- managedtenants/data/selectorsyncset.yaml.j2
Fixed namespace logic for `pullSecret`
> Fixed secret-namespace logic

- managedtenants/bundles/index_builder.py
Reverts mt-sre/managed-tenants-cli#162
> Revert "MTSRE-489 Bundles use digest format"

- managedtenants/cli/validate_imageset.py
- setup.py
- Adds a new command for validating imagesets to be used by CPaaS in a container.
> [MTSRE-538] feat: adding new command entrypoint for imageset validation

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/bundles/index_builder.py
- managedtenants/core/addons_loader/addon.py
- managedtenants/schemas/metadata.schema.yaml
- tests/addons/test_addon.py
- tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml
Remove `destinationSecretName` and related tests.
> remove `destinationSecretName` property

- managedtenants/core/addons_loader/addon.py
- tests/addons/test_addon.py
- tests/testdata/addons/mock-operator-with-duplicate-keys/metadata/stage/addon.yaml
- tests/testutils/addon_helpers.py
https://issues.redhat.com/browse/MTSRE-559
> MTSRE-559 | Validates keys are unique in addon.yaml

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/schemas/metadata.schema.yaml
- tests/testdata/addons/mock-operator-with-secrets/metadata/stage/addon.yaml
We need to add each field individually. Also, we have to validate them agains app-interface.
> Addons version and fields to secrets schema

- docs/tenants/zz_imageset_schema_generated.md
- managedtenants/schemas/imageset.schema.yaml
- managedtenants/utils/ocm.py
Updates ocm client to include the following attributes:
- additionalCatalogSources
- pullSecretName
- subscriptionConfig
Attributes defined in the imageset file takes precedence over the attributes defined in the metadata file.
> Update ocm client

- managedtenants/data/selectorsyncset.yaml.j2
> [MTSRE-600] fix: typo in spec 

- managedtenants/bundles/cli.py
> enable imageset creation for dbaas operator

- managedtenants/schemas/shared/config.json
- tests/addons/test_addon.py
- tests/testdata/addons/mock-operator-with-imagesets/addonimagesets/stage/mock-operator-invalid-env-value.v0.0.9.yml
> update regex validation for the env value attribute

- README.md
- Update Release Instructions in README.md
> Update Release Instructions in README.md

- Dockerfile.test
> pin python 3.9 image used in dockerfile.test

- docs/tenants/zz_metadata_schema_generated.md
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/schemas/metadata.schema.yaml
- tests/sss/test_catalogue_source.py
- tests/sss/test_sss_walker.py
- tests/testdata/addons/test-operator/metadata/integration/addon.yaml
Removing `pullSecret` from `metadata.schema.yaml`.
> [MTSRE-669] removing pullSecret from metadata schema

- README.md
- managedtenants/cli/__init__.py
- managedtenants/data/selectorsyncset.yaml.j2
- managedtenants/utils/ocm.py
- tests/utils/test_ocm.py
- modified X
- modified Y
- modified Z
> add client credentials support

- managedtenants/bundles/index_builder.py
Updating the new index image for OPM v1.24.0 present in the mt-sre quay org.
> [MTSRE-796] opm-ubi image update

- managedtenants/bundles/addon_bundles.py
- managedtenants/bundles/addon_package.py
- managedtenants/bundles/bundle_builder.py
- managedtenants/bundles/cli.py
- managedtenants/bundles/docker_api.py
- managedtenants/bundles/imageset.py
- managedtenants/bundles/imageset_creator.py
- managedtenants/bundles/index_builder.py
- managedtenants/bundles/package_builder.py
- managedtenants/core/addons_loader/manifest.py
- setup.py
- tests/addons/test_addon.py
- tests/sss/test_federated_metrics.py
- tests/testutils/addon_helpers.py
- tests/utils/test_ocm.py
- Added support for build/push Addon Package on Managed Tenants Bundles
- Added VERSION file support to Managed Tenants Bundles, to define the Addon Version
> [MTSRE-888] Addon Package Support for MTB

- managedtenants/data/selectorsyncset.yaml.j2
- modified X
- modified Y
- modified Z
> feat: changing enabled type to boolean from string
